### ISSUE TITLE
Can't edit setting

### ISSUE THREAD

**Issue by hi-hai** [absszero/sublime-jester#3]
When choose `edit plugin setting`, it shows an error `The settings file "res://Packages/sublime_jester/Jester.sublime-settings" could not be opened`

Sublime Text 4.

**Comment by absszero** [comment]
> When choose `edit plugin setting`, it shows an error `The settings file "res://Packages/sublime_jester/Jester.sublime-settings" could not be opened`
> 
> Sublime Text 4.

What's your OS?

**Comment by absszero** [comment]
The issue was fixed, install the latest version

**Comment by sohansubhash** [comment]
I'm still seeing this error. I'm on macOS Monterey.

**Comment by absszero** [comment]
> I'm still seeing this error. I'm on macOS Monterey.

Could you reinstall the plugin and also provider more details.
